# Generated by Django 2.2.4 on 2019-08-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190823_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
