# Generated by Django 2.2.4 on 2019-08-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usermovierating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMovieRating',
        ),
    ]
