# Generated by Django 2.2.4 on 2019-08-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190830_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeansresult',
            name='clusterlist',
            field=models.TextField(),
        ),
    ]
