# Generated by Django 2.2.4 on 2019-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190830_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeansresult',
            name='clusterlist',
            field=models.CharField(max_length=1000),
        ),
    ]
