# Generated by Django 2.2.4 on 2019-08-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190830_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeansresult',
            name='clusterlist',
            field=models.CharField(max_length=1000),
        ),
    ]
