# Generated by Django 2.2.4 on 2019-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190830_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=20000)),
            ],
        ),
        migrations.AlterField(
            model_name='kmeansresult',
            name='clusterlist',
            field=models.CharField(max_length=20000),
        ),
    ]
