# Generated by Django 2.2.4 on 2019-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_movieposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieposter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
