# Generated by Django 2.2.4 on 2019-09-25 09:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_movieposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.IntegerField(default=api.models.number, primary_key=True, serialize=False, unique=True)),
                ('ImdbLink', models.CharField(max_length=500)),
                ('posterUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
