# Generated by Django 2.2.4 on 2019-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190923_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieposter',
            name='posterUrl',
            field=models.CharField(max_length=20000),
        ),
    ]
