# Generated by Django 2.2.4 on 2019-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviePoster',
        ),
    ]
